export const FETCH_DATA_PIZZA = 'FETCH_DATA_PIZZA'
export const FETCH_DATA_BEVERAGE = 'FETCH_DATA_BEVERAGE'
export const FETCH_DATA_DESSERT = 'FETCH_DATA_DESSERT'
export const FETCH_DATA_SIDEDISH = 'FETCH_DATA_SIDEDISH'
